package admin;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import rooms.*;
import database.DatabaseConnector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shakil
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdmnPanel
     */
    
    Connection connection;
    ResultSet resultSet;
    PreparedStatement preparedStatement;
    
    public AdminPanel() {
        super("New Room Informations");
        initComponents();
        connection = DatabaseConnector.connectDatabase();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnAddRoom = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jBtnAvailable = new javax.swing.JButton();
        jNewAdmin = new javax.swing.JButton();
        btnUpdatePrice = new javax.swing.JButton();
        btnRoomInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 53, 7), 2), "Admin Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 102, 0))); // NOI18N

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(4, 114, 114));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAddRoom.setBackground(new java.awt.Color(255, 255, 255));
        btnAddRoom.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnAddRoom.setForeground(new java.awt.Color(4, 114, 114));
        btnAddRoom.setText("Add New Room");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(4, 114, 114));
        btnDelete.setText("Remove Room");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jBtnAvailable.setBackground(new java.awt.Color(255, 255, 255));
        jBtnAvailable.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jBtnAvailable.setForeground(new java.awt.Color(4, 114, 114));
        jBtnAvailable.setText("Make Room Available");
        jBtnAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAvailableActionPerformed(evt);
            }
        });

        jNewAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jNewAdmin.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jNewAdmin.setForeground(new java.awt.Color(4, 114, 114));
        jNewAdmin.setText("Add New Admin");
        jNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewAdminActionPerformed(evt);
            }
        });

        btnUpdatePrice.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdatePrice.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnUpdatePrice.setForeground(new java.awt.Color(4, 114, 114));
        btnUpdatePrice.setText("Update Room Price");
        btnUpdatePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePriceActionPerformed(evt);
            }
        });

        btnRoomInfo.setBackground(new java.awt.Color(255, 255, 255));
        btnRoomInfo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnRoomInfo.setForeground(new java.awt.Color(4, 114, 114));
        btnRoomInfo.setText("Room Status");
        btnRoomInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnUpdatePrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnAvailable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addComponent(btnRoomInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jNewAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnAddRoom)
                .addGap(25, 25, 25)
                .addComponent(btnDelete)
                .addGap(25, 25, 25)
                .addComponent(btnRoomInfo)
                .addGap(25, 25, 25)
                .addComponent(jBtnAvailable)
                .addGap(25, 25, 25)
                .addComponent(jNewAdmin)
                .addGap(25, 25, 25)
                .addComponent(btnUpdatePrice)
                .addGap(25, 25, 25)
                .addComponent(btnLogout)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAvailableActionPerformed
        // TODO add your handling code here:
        UpdateRoomStatus updateRoomStatus = new UpdateRoomStatus();
        updateRoomStatus.updateRoomStatus();
    }//GEN-LAST:event_jBtnAvailableActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Admin admin = new Admin();
        admin.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewAdminActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        NewAdmin newAdmin = new NewAdmin();
        newAdmin.setVisible(true);
    }//GEN-LAST:event_jNewAdminActionPerformed

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AddNewRoom addNewRoom = new AddNewRoom();
        addNewRoom.setVisible(true);
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void btnUpdatePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePriceActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        RoomPrice roomPrice = new RoomPrice();
        roomPrice.setVisible(true);
    }//GEN-LAST:event_btnUpdatePriceActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        RemoveRoom removeRoom = new RemoveRoom();
        removeRoom.setVisible(true);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRoomInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomInfoActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        RoomStatus status = new RoomStatus();
        status.setVisible(true);
    }//GEN-LAST:event_btnRoomInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRoomInfo;
    private javax.swing.JButton btnUpdatePrice;
    private javax.swing.JButton jBtnAvailable;
    private javax.swing.JButton jNewAdmin;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
